version: "2.3"

services:
    url-shortener-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/url-shortener/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/url-shortener:rw
        ports:
          - 8080:8080
        working_dir: /url-shortener
        entrypoint:
          - ./tests/run_as_user.sh
